### ISSUE TITLE
Werkzeug 0.11.10 throws WinError 10038

### ISSUE THREAD

**Issue by BennyAlex** [pallets/werkzeug#993]
I am using Python 3.5 on windows. On my flask app with Werkzeug 0.11.10  the following error occurs:

```
Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 259-753-854
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python35\Lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\python35\Lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Envs\myproject\lib\site-packages\werkzeug\serving.py", line 656, in inner
    fd=fd)
  File "C:\Users\admin\Envs\myproject\lib\site-packages\werkzeug\serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Users\admin\Envs\myproject\lib\site-packages\werkzeug\serving.py", line 462, in __init__
    socket.SOCK_STREAM)
  File "c:\python35\Lib\socket.py", line 450, in fromfd
    nfd = dup(fd)
OSError: [WinError 10038] an operation was attempted on something that is not a socket
```

Strange: With Werkzeug 0.10.4 all works fine and on the computers from my business colleagues, working on the same app, no problems with Werkzeug 0.11.10  o.0

**Comment by untitaker** [comment]
Please post this question on StackOverflow instead as long there is not clearly an issue with Werkzeug itself.

**Comment by davidism** [comment]
Already asked here: http://stackoverflow.com/questions/39067544/running-flask-app-on-windows-raises-an-operation-was-attempted-on-something-tha

**Comment by BennyAlex** [comment]
@davidism I already saw this but there is no solution. And I thought the Werkzeug developers could know something...

**Comment by aaossa** [comment]
Hi, I'm having the same problem (Related: https://github.com/pallets/flask/issues/2194). It seems like Flask believes that opening a socket by file descriptor is possible [werkzeug/serving.py#L97], wich is determined by [werkzeug/serving.py#L723]. Finally, the problem falls to [python/socket.py#L460] and [python/socket.py#L632]. 

A few days ago this Flask debug mode worked, I only updated Flask and Werkzeug. I'll try to check if the problem comes from Flask, Werkzeug, Python or Windows.

[werkzeug/serving.py#L97]: https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L97
[werkzeug/serving.py#L723]: https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L723
[python/socket.py#L460]: https://github.com/python/cpython/blob/master/Lib/socket.py#L460
[python/socket.py#L632]: https://github.com/python/cpython/blob/master/Lib/socket.py#L632

**Comment by aaossa** [comment]
I had to install Werkzeug 0.10.4 to make it work:

```
(venv) PATH>python demo.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 320-320-654
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\program files\python35\Lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\program files\python35\Lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "PATH\venv\lib\site-packages\werkzeug\serving.py", line 696, in inner
    fd=fd)
  File "PATH\venv\lib\site-packages\werkzeug\serving.py", line 590, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "PATH\venv\lib\site-packages\werkzeug\serving.py", line 499, in __init__
    socket.SOCK_STREAM)
  File "c:\program files\python35\Lib\socket.py", line 450, in fromfd
    nfd = dup(fd)
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket


(venv) PATH>pip install Werkzeug==0.10.4
Collecting Werkzeug==0.10.4
  Using cached Werkzeug-0.10.4-py2.py3-none-any.whl
Installing collected packages: Werkzeug
  Found existing installation: Werkzeug 0.12
    Uninstalling Werkzeug-0.12:
      Successfully uninstalled Werkzeug-0.12
Successfully installed Werkzeug-0.10.4

(venv) PATH>python demo.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [11/Mar/2017 17:16:39] "GET / HTTP/1.1" 200 -

(venv) PATH>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.3)
click (6.7)
Flask (0.12)
itsdangerous (0.24)
Jinja2 (2.9.5)
MarkupSafe (1.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
setuptools (34.3.2)
six (1.10.0)
Werkzeug (0.10.4)
wheel (0.29.0)
```

**Comment by untitaker** [comment]
So this issue is fixed after all?

On 11 March 2017 21:22:32 CET, Antonio Ossa <notifications@github.com> wrote:
>I had to install Werkzeug 0.10.4 to make it work:
>
>```
>(venv) PATH>python demo.py
> * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> * Restarting with stat
> * Debugger is active!
> * Debugger PIN: 320-320-654
>Exception in thread Thread-1:
>Traceback (most recent call last):
>File "c:\program files\python35\Lib\threading.py", line 914, in
>_bootstrap_inner
>    self.run()
>  File "c:\program files\python35\Lib\threading.py", line 862, in run
>    self._target(*self._args, **self._kwargs)
>File "PATH\venv\lib\site-packages\werkzeug\serving.py", line 696, in
>inner
>    fd=fd)
>File "PATH\venv\lib\site-packages\werkzeug\serving.py", line 590, in
>make_server
>    passthrough_errors, ssl_context, fd=fd)
>File "PATH\venv\lib\site-packages\werkzeug\serving.py", line 499, in
>__init__
>    socket.SOCK_STREAM)
>  File "c:\program files\python35\Lib\socket.py", line 450, in fromfd
>    nfd = dup(fd)
>OSError: [WinError 10038] Se intentó realizar una operación en un
>elemento que no es un socket
>
>
>(venv) PATH>pip install Werkzeug==0.10.4
>Collecting Werkzeug==0.10.4
>  Using cached Werkzeug-0.10.4-py2.py3-none-any.whl
>Installing collected packages: Werkzeug
>  Found existing installation: Werkzeug 0.12
>    Uninstalling Werkzeug-0.12:
>      Successfully uninstalled Werkzeug-0.12
>Successfully installed Werkzeug-0.10.4
>
>(venv) PATH>python demo.py
> * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> * Restarting with stat
>127.0.0.1 - - [11/Mar/2017 17:16:39] "GET / HTTP/1.1" 200 -
>
>(venv) PATH>pip list
>DEPRECATION: The default format will switch to columns in the future.
>You can use --format=(legacy|columns) (or define a
>format=(legacy|columns) in your pip.conf under the [list] section) to
>disable this warning.
>appdirs (1.4.3)
>click (6.7)
>Flask (0.12)
>itsdangerous (0.24)
>Jinja2 (2.9.5)
>MarkupSafe (1.0)
>packaging (16.8)
>pip (9.0.1)
>pyparsing (2.2.0)
>setuptools (34.3.2)
>six (1.10.0)
>Werkzeug (0.10.4)
>wheel (0.29.0)
>```
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/werkzeug/issues/993#issuecomment-285897286

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aaossa** [comment]
No, is not fixed because the latest Werkzeug versions break the code. I can't use any 0.11 or 0.12 version. I was trying to find if a 0.11 version worked but they didn't.

### Code 

```python
import flask

app = flask.Flask(__name__)


@app.route("/")
def hello_world():
    return "Hello, World!"

if __name__ == '__main__':
    app.run(debug=True)
```

### Running different versions

| Werkzeug version | Error type | Full error |
| :---: | :---: | :---: |
| 0.11 <br> 0.11.1 | `OSError` | `OSError: [Errno 9] Bad file descriptor` |
| 0.11.2 <br> 0.11.3 <br> 0.11.4 <br> 0.11.5 <br> 0.11.7 <br> 0.11.8 <br> 0.11.9 <br> 0.11.10 <br> 0.11.11 <br> 0.11.12 <br> 0.11.13 <br> 0.11.15 <br> 0.12 | `OSError` | `OSError: [WinError 10038] an operation was attempted on something that is not a socket` |
| 0.11.6 | `TypeError` | `TypeError: Unicode-objects must be encoded before hashing` |
| 0.11.14 | `TypeError` | `TypeError: Cannot create a consistent method resolution order (MRO) for bases object, BaseWSGIServer`
| 0.10.4 | - | Success |

### Other versions

```
(venv) PATH>python --version
Python 3.5.2

(venv) PATH>pip freeze
appdirs==1.4.3
click==6.7
Flask==0.12
itsdangerous==0.24
Jinja2==2.9.5
MarkupSafe==1.0
packaging==16.8
pyparsing==2.2.0
six==1.10.0
Werkzeug==??? # This was the one changing
```

**Comment by aaossa** [comment]
Maybe it's related to [this](https://docs.python.org/3.5/library/socket.html#socket.socket.fileno):

> `socket.fileno()`
> Return the socket’s file descriptor (a small integer), or -1 on failure. This is useful with select.select().
> 
> **Under Windows the small integer returned by this method cannot be used where a file descriptor can be used (such as os.fdopen()). Unix does not have this limitation.**

If I set `can_open_by_fd` to `False` in [serving.py#L97] my app works as expected. How are they related? Because in [serving.py#L723] the boolean is used to choose is the file descriptor can be reused. After this change my app is able to load and the debug mode works as expected. It seems like the only difference is that the socket file descriptor changes after each reload. Obviously this is not a solution, do you think that this is the way to go?

[serving.py#L97]: https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L97
[serving.py#L723]: https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L723

**Comment by aaossa** [comment]
@untitaker  I think that because of [`socket.fileno` docs](https://docs.python.org/3.5/library/socket.html#socket.socket.fileno) we need to detect the Windows plaform (you can see the [source code](https://github.com/python/cpython/blob/master/Lib/socket.py#L632), where no checks are made):

> **Under Windows the small integer returned by this method cannot be used where a file descriptor can be used (such as os.`fdopen()`)**. Unix does not have this limitation.

How does Python do that? I found [`os.supports_bytes_environ` docs](https://docs.python.org/3.5/library/socket.html#socket.socket.fileno):

> `True` if the native OS type of the environment is bytes (eg. `False` on Windows).

You can see the in [source code](https://github.com/python/cpython/blob/master/Lib/os.py#L768) the line where this variable is defined. They use `'nt' in sys.builtin_module_names` ([this line](https://github.com/python/cpython/blob/master/Lib/os.py#L68)) to detect the Windows platorm. I think that a possible solution could be:

```python
# Use a flag if we can use socket.fileno output
# (Possible location to create variable: 
# https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L98)
can_use_fileno_output = ('nt' not in sys.builtin_module_names) 

# If we can open the socket by file descriptor **AND we can use socket.fileno output**
# (Line: https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L723)
if can_open_by_fd and can_use_fileno_output:
    # Reuse file descriptor
    ...
```

---

Also, I found https://github.com/pallets/werkzeug/issues/805, where the version seems to be 0.11.1, based on the reported error and looking at [the table I posted before](https://github.com/pallets/werkzeug/issues/993#issuecomment-285899513). It seems like [the commit](https://github.com/pallets/werkzeug/commit/f0012580ba565f46763d6d6ad7d98d60661cb5ae) solved the `OSError: [Errno 9] Bad file descriptor`, but didn't handle `OSError: [WinError 10038] an operation was attempted on something that is not a socket`. I don't know why :sweat_smile:

**Comment by untitaker** [comment]
I think the fix could look something like this: can_open_by_fd = not WIN and hasattr(...)

Where WIN is from the _compat module. Do you agree, and do you want to make a PR for this?

On 12 March 2017 00:17:51 CET, Antonio Ossa <notifications@github.com> wrote:
>@untitaker  I think that because of [`socket.fileno`
>docs](https://docs.python.org/3.5/library/socket.html#socket.socket.fileno)
>we need to detect the Windows plaform (you can see the [source
>code](https://github.com/python/cpython/blob/master/Lib/socket.py#L632),
>where no checks are made):
>
>> **Under Windows the small integer returned by this method cannot be
>used where a file descriptor can be used (such as os.`fdopen()`)**.
>Unix does not have this limitation.
>
>How does Python do that? I found [`os.supports_bytes_environ`
>docs](https://docs.python.org/3.5/library/socket.html#socket.socket.fileno):
>
>> `True` if the native OS type of the environment is bytes (eg. `False`
>on Windows).
>
>You can see the in [source
>code](https://github.com/python/cpython/blob/master/Lib/os.py#L768) the
>line where this variable is defined. They use `'nt' in
>sys.builtin_module_names` ([this
>line](https://github.com/python/cpython/blob/master/Lib/os.py#L68)) to
>detect the Windows platorm. I think that a possible solution could be:
>
>```python
># Use a flag if we can use socket.fileno output
># (Possible location to create variable: 
>#
>https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L98)
>can_use_fileno_output = ('nt' not in sys.builtin_module_names) 
>
># If we can open the socket by file descriptor **AND we can use
>socket.fileno output**
># (Line:
>https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L723)
>if can_open_by_fd and can_use_fileno_output:
>    # Reuse file descriptor
>    ...
>```
>
>---
>
>Also, I found https://github.com/pallets/werkzeug/issues/805, where the
>version seems to be 0.11.1, based on the reported error and looking at
>[the table I posted
>before](https://github.com/pallets/werkzeug/issues/993#issuecomment-285899513).
>It seems like [the
>commit](https://github.com/pallets/werkzeug/commit/f0012580ba565f46763d6d6ad7d98d60661cb5ae)
>solved the `OSError: [Errno 9] Bad file descriptor`, but didn't handle
>`OSError: [WinError 10038] an operation was attempted on something that
>is not a socket`. I don't know why :sweat_smile:
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/werkzeug/issues/993#issuecomment-285908118

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aaossa** [comment]
Yes, I agree with that solution. I'll create the PR in a couple of minutes :ok_hand:
